# Site settings
title: Douglas Doner
subTitle: Front End Developer
email: ddoner02@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Front-end Developer who specializes in HTML, CSS, and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  dougdoner

# Build settings
markdown: kramdown

#collections settings
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/